daysUntilStale: 14
daysUntilClose: false
staleLabel: stale
markComment: >
  This issue has been automatically marked as overdue because it has not had
  recent activity. Thank you for your contributions.
closeComment: false
